# -*- coding: utf-8 -*-
"""translate.py - 联赛+队名（补充版）"""

LEAGUE_MAP = {
    "soccer_epl": "英超", "soccer_efl_champ": "英冠",
    "soccer_england_efl_cup": "英联赛杯",
    "soccer_england_league1": "英甲", "soccer_england_league2": "英乙",
    "soccer_spain_la_liga": "西甲", "soccer_spain_segunda_division": "西乙",
    "soccer_italy_serie_a": "意甲", "soccer_italy_serie_b": "意乙",
    "soccer_germany_bundesliga": "德甲", "soccer_germany_bundesliga2": "德乙",
    "soccer_germany_liga3": "德丙", "soccer_germany_dfb_pokal": "德国杯",
    "soccer_france_ligue_one": "法甲", "soccer_france_ligue_two": "法乙",
    "soccer_netherlands_eredivisie": "荷甲",
    "soccer_portugal_primeira_liga": "葡超",
    "soccer_belgium_first_div": "比甲",
    "soccer_turkey_super_league": "土超",
    "soccer_austria_bundesliga": "奥地利甲",
    "soccer_switzerland_superleague": "瑞士超",
    "soccer_greece_super_league": "希腊超",
    "soccer_denmark_superliga": "丹超",
    "soccer_norway_eliteserien": "挪超",
    "soccer_sweden_allsvenskan": "瑞超",
    "soccer_sweden_superettan": "瑞典甲",
    "soccer_finland_veikkausliiga": "芬超",
    "soccer_spl": "苏超", "soccer_league_of_ireland": "爱尔兰超",
    "soccer_uefa_champs_league": "欧冠",
    "soccer_uefa_europa_league": "欧联",
    "soccer_uefa_europa_conference_league": "欧协联",
    "soccer_uefa_nations_league": "欧国联",
    "soccer_conmebol_copa_libertadores": "解放者杯",
    "soccer_conmebol_copa_sudamericana": "南美杯",
    "soccer_usa_mls": "美职", "soccer_mexico_ligamx": "墨超",
    "soccer_brazil_campeonato": "巴甲", "soccer_brazil_serie_b": "巴乙",
    "soccer_argentina_primera_division": "阿甲",
    "soccer_chile_campeonato": "智利甲",
    "soccer_korea_kleague1": "韩K联",
    "soccer_australia_aleague": "澳超",
    # 中文联赛名（直接映射）
    "英超": "英超", "西甲": "西甲", "意甲": "意甲",
    "德甲": "德甲", "法甲": "法甲", "欧冠": "欧冠",
    "欧联": "欧联", "欧协联": "欧协联", "欧国联": "欧国联",
    "荷甲": "荷甲", "葡超": "葡超", "比甲": "比甲",
    "土超": "土超", "美职": "美职", "墨超": "墨超",
    "巴甲": "巴甲", "阿甲": "阿甲", "韩K联": "韩K联",
    "国际赛": "国际友谊", "国际友谊": "国际友谊",
    "亚运男足": "亚运男足", "球会友谊": "球会友谊",
}


TEAM_MAP = {
    # ============ 欧国联国家队 ============
    "Andorra": "安道尔", "Malta": "马耳他",
    "Austria": "奥地利", "Israel": "以色列",
    "Norway": "挪威", "Denmark": "丹麦",
    "Netherlands": "荷兰", "Germany": "德国",
    "Serbia": "塞尔维亚", "Greece": "希腊",
    "Kosovo": "科索沃", "Republic of Ireland": "爱尔兰",
    "Ireland": "爱尔兰", "Liechtenstein": "列支敦士登",
    "Lithuania": "立陶宛", "Portugal": "葡萄牙",
    "Wales": "威尔士", "Armenia": "亚美尼亚",
    "Latvia": "拉脱维亚", "Georgia": "格鲁吉亚",
    "Northern Ireland": "北爱尔兰", "Italy": "意大利",
    "Belgium": "比利时", "Poland": "波兰",
    "Bosnia & Herzegovina": "波黑", "Bosnia and Herzegovina": "波黑",
    "Montenegro": "黑山", "Cyprus": "塞浦路斯",
    "Turkey": "土耳其", "France": "法国",
    "Hungary": "匈牙利", "Ukraine": "乌克兰",
    "Sweden": "瑞典", "Romania": "罗马尼亚",
    "Slovenia": "斯洛文尼亚", "Scotland": "苏格兰",
    "Bulgaria": "保加利亚", "Luxembourg": "卢森堡",
    "Iceland": "冰岛", "Estonia": "爱沙尼亚",
    "Faroe Islands": "法罗群岛", "Kazakhstan": "哈萨克斯坦",
    "Spain": "西班牙", "Switzerland": "瑞士",
    "Czech Republic": "捷克", "Czechia": "捷克",
    "Croatia": "克罗地亚", "Finland": "芬兰",
    "Albania": "阿尔巴尼亚", "Belarus": "白俄罗斯",
    "England": "英格兰", "Slovakia": "斯洛伐克",
    "North Macedonia": "北马其顿", "Moldova": "摩尔多瓦",
    "San Marino": "圣马力诺", "Gibraltar": "直布罗陀",
    "Azerbaijan": "阿塞拜疆",
    # ============ 其他常见国家队 ============
    "Brazil": "巴西", "Argentina": "阿根廷",
    "Uruguay": "乌拉圭", "Colombia": "哥伦比亚",
    "Mexico": "墨西哥", "USA": "美国", "United States": "美国",
    "Japan": "日本", "South Korea": "韩国", "Korea Republic": "韩国",
    "Australia": "澳大利亚", "Iran": "伊朗",
    "Saudi Arabia": "沙特", "Morocco": "摩洛哥",
    "Egypt": "埃及", "Nigeria": "尼日利亚",
    "China": "中国", "China PR": "中国",
    "Maldives": "马尔代夫", "Ecuador": "厄瓜多尔",
    # ============ 英超 ============
    "Arsenal": "阿森纳", "Aston Villa": "阿斯顿维拉",
    "Bournemouth": "伯恩茅斯", "Brentford": "布伦特福德",
    "Brighton and Hove Albion": "布莱顿", "Brighton & Hove Albion": "布莱顿",
    "Chelsea": "切尔西", "Crystal Palace": "水晶宫",
    "Everton": "埃弗顿", "Fulham": "富勒姆",
    "Ipswich Town": "伊普斯维奇", "Leeds United": "利兹联",
    "Leicester City": "莱斯特城", "Liverpool": "利物浦",
    "Manchester City": "曼城", "Manchester United": "曼联",
    "Newcastle United": "纽卡斯尔", "Nottingham Forest": "诺丁汉森林",
    "Southampton": "南安普顿", "Tottenham Hotspur": "热刺",
    "Tottenham": "热刺", "West Ham United": "西汉姆联",
    "Wolverhampton Wanderers": "狼队", "Wolves": "狼队",
    "Coventry City": "考文垂", "Hull City": "赫尔城",
    "Sunderland": "桑德兰",
    # ============ 西甲 ============
    "Real Madrid": "皇家马德里", "Barcelona": "巴塞罗那",
    "Atletico Madrid": "马德里竞技", "Atlético Madrid": "马德里竞技",
    "Sevilla": "塞维利亚", "Real Betis": "皇家贝蒂斯",
    "Valencia": "瓦伦西亚", "Real Sociedad": "皇家社会",
    "Villarreal": "比利亚雷亚尔", "Athletic Bilbao": "毕尔巴鄂",
    "Athletic Club": "毕尔巴鄂", "Getafe": "赫塔费",
    "Rayo Vallecano": "巴列卡诺", "Celta Vigo": "塞尔塔",
    "Mallorca": "马洛卡", "Girona": "赫罗纳",
    "Alavés": "阿拉维斯", "Alaves": "阿拉维斯",
    "Elche CF": "埃尔切", "Elche": "埃尔切",
    "Espanyol": "西班牙人", "Osasuna": "奥萨苏纳",
    "CA Osasuna": "奥萨苏纳", "Levante": "莱万特",
    "Málaga": "马拉加", "Malaga": "马拉加",
    "Deportivo La Coruña": "拉科鲁尼亚",
    "Deportivo La Coruna": "拉科鲁尼亚",
    "Real Valladolid": "皇家瓦拉多利德",
    "UD Las Palmas": "拉斯帕尔马斯", "Las Palmas": "拉斯帕尔马斯",
    # ============ 德甲 ============
    "Bayern Munich": "拜仁慕尼黑", "Borussia Dortmund": "多特蒙德",
    "RB Leipzig": "莱比锡", "Bayer Leverkusen": "勒沃库森",
    "Eintracht Frankfurt": "法兰克福", "VfB Stuttgart": "斯图加特",
    "SC Freiburg": "弗赖堡", "Union Berlin": "柏林联合",
    "Borussia Monchengladbach": "门兴",
    "Borussia Mönchengladbach": "门兴",
    "TSG Hoffenheim": "霍芬海姆", "Hoffenheim": "霍芬海姆",
    "FC Schalke 04": "沙尔克04", "Schalke 04": "沙尔克04",
    "FSV Mainz 05": "美因茨", "Mainz 05": "美因茨",
    "Werder Bremen": "不莱梅", "Augsburg": "奥格斯堡",
    "SC Paderborn": "帕德博恩", "Paderborn": "帕德博恩",
    "Hamburger SV": "汉堡", "1. FC Köln": "科隆",
    "1. FC Koln": "科隆", "FC Koln": "科隆",
    "Elversberg": "埃尔弗斯贝格", "VfL Wolfsburg": "沃尔夫斯堡",
    # ============ 意甲 ============
    "Inter Milan": "国际米兰", "Inter": "国际米兰",
    "AC Milan": "AC米兰", "Milan": "AC米兰",
    "Juventus": "尤文图斯", "Napoli": "那不勒斯",
    "AS Roma": "罗马", "Roma": "罗马",
    "Lazio": "拉齐奥", "Atalanta BC": "亚特兰大", "Atalanta": "亚特兰大",
    "Fiorentina": "佛罗伦萨", "Bologna": "博洛尼亚",
    "Torino": "都灵", "Udinese": "乌迪内斯",
    "Genoa": "热那亚", "Lecce": "莱切",
    "Parma": "帕尔马", "Como": "科莫",
    "Venezia": "威尼斯", "Monza": "蒙扎",
    "Cagliari": "卡利亚里", "Sassuolo": "萨索洛",
    "Frosinone": "弗罗西诺内",
    # ============ 法甲 ============
    "Paris Saint Germain": "巴黎圣日耳曼",
    "Paris Saint-Germain": "巴黎圣日耳曼",
    "PSG": "巴黎圣日耳曼", "Marseille": "马赛",
    "AS Monaco": "摩纳哥", "Monaco": "摩纳哥",
    "Lyon": "里昂", "Lille": "里尔",
    "Nice": "尼斯", "Rennes": "雷恩",
    "Strasbourg": "斯特拉斯堡", "Toulouse": "图卢兹",
    "Nantes": "南特", "Montpellier": "蒙彼利埃",
    "Brest": "布雷斯特", "Reims": "兰斯",
    "Le Havre": "勒阿弗尔", "Auxerre": "欧塞尔",
    "Angers": "昂热", "Metz": "梅斯",
    "Troyes": "特鲁瓦", "Lorient": "洛里昂",
    "RC Lens": "朗斯", "Lens": "朗斯",
    "Le Mans FC": "勒芒", "Paris FC": "巴黎FC",
    # ============ 欧冠常见 ============
    "Galatasaray": "加拉塔萨雷", "Viking FK": "维京",
    "Sporting Lisbon": "葡萄牙体育", "Sporting CP": "葡萄牙体育",
    "PSV Eindhoven": "埃因霍温", "PSV": "埃因霍温",
    "Feyenoord": "费耶诺德", "Club Brugge": "布鲁日",
    "AEK Athens": "AEK雅典", "Shakhtar Donetsk": "顿涅茨克矿工",
    "LASK": "LASK林茨", "Bodø/Glimt": "博多闪耀",
    "Bodo/Glimt": "博多闪耀", "Sabah FK": "萨巴赫",
    "Slavia Praha": "布拉格斯拉维亚",
    "ŠK Slovan Bratislava": "布拉迪斯拉发",
    "SK Slovan Bratislava": "布拉迪斯拉发",
    "Fenerbahce": "费内巴切", "Porto": "波尔图",
    "Benfica": "本菲卡", "Ajax": "阿贾克斯",
    "Celtic": "凯尔特人", "Rangers": "格拉斯哥流浪者",
    "Salzburg": "萨尔茨堡", "Red Bull Salzburg": "萨尔茨堡",
    "Young Boys": "年轻人", "FC Copenhagen": "哥本哈根",
}


def cn_league(name):
    if not name:
        return ""
    name = str(name).strip()
    return LEAGUE_MAP.get(name, name)


def cn_team(name):
    if not name:
        return ""
    name = str(name).strip()
    return TEAM_MAP.get(name, name)
